name: Lint

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  statuses: write

jobs:
  run-lint:
    name: Run Lint
    uses: mehdi-behrooz/freiheit-workflows/.github/workflows/lint.yaml@main
    with:
      environment: |
        VALIDATE_GO=false
        VALIDATE_GO_MODULES=false
